import '../styles/globals.css'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import type { AppProps } from 'next/app'
import Header from '../components/header'
import Footer from '../components/footer'
import 'bootstrap/dist/css/bootstrap.css';
import "bootstrap-icons/font/bootstrap-icons.css";

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Ecommerce</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main className={styles.main}>
      <div className="container">
        <Component {...pageProps} />
      </div>
    </main>
    <Footer />
  </>
}

export default MyApp
